### ISSUE TITLE
初始化项目error

### ISSUE THREAD

**Issue by grace5925** [jdf2e/Gaea4#1]
正在下载模版events.js:167
      throw er; // Unhandled 'error' event

模板下载失败

**Comment by wangnan19900401** [comment]
> 正在下载模版events.js:167
> throw er; // Unhandled 'error' event
> 
> 模板下失败
node>=8.9.0  全局安装后，需要在文件夹下g2 init name 。如果有还有问题，请说一下操作步骤

**Comment by wangnan41** [comment]
@grace5925  请确保node>=8.9.0 另外全局安装后 ,需要在文件夹下g2 init name 初始化项目，如果还有问题，请仔细描述一下操作步骤，或者截图

**Comment by grace5925** [comment]
[cid:CD030AC3-8652-48BF-839B-3A97B4035F73@mailmaster]

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=grace5925&uid=grace5925%40hotmail.com&iconUrl=http%3A%2F%2Fmail-online.nosdn.127.net%2Fsm045a8457384a493011ae5a9b5308dc8c.jpg&items=%5B%22grace5925%40hotmail.com%22%5D>
[http://mail-online.nosdn.127.net/sm045a8457384a493011ae5a9b5308dc8c.jpg]
grace5925

grace5925@hotmail.com

签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81> 定制
在2019年2月15日 14:30，wangnan19900401<notifications@github.com><mailto:notifications@github.com> 写道：

@grace5925<https://github.com/grace5925> 请确保node>=8.9.0 另外全局安装后 ,需要在文件夹下g2 init name 初始化项目，如果还有问题，请仔细描述一下操作步骤，或者截图

**Comment by grace5925** [comment]
@wangnan41 node版本10.13.0，脚手架是全局安装的，我在桌面或者桌面的文件夹里init项目都是初始化失败，每次都是停在下载模板的地方

**Comment by wangnan41** [comment]
@grace5925 
我测试了10.13.0  gaea 版本v0.7.4 选择vue模版下载，测试正常
![1093f665-27d4-46dc-a542-822a019567a7](https://user-images.githubusercontent.com/9304420/52942993-12d4c600-33a7-11e9-8f18-b9fca9a40f00.jpg)

**Comment by grace5925** [comment]
@wangnan41 我把版本更新又试了一次，但问题依然存在
![tim 20190218180421](https://user-images.githubusercontent.com/7194782/52943422-10bf3700-33a8-11e9-92f9-09ae39851308.png)

**Comment by wangnan41** [comment]
@grace5925  你新建一个文件夹试试 ，在该文件夹下起项目

**Comment by grace5925** [comment]
@wangnan41 还是一样。。
![tim 20190218181430](https://user-images.githubusercontent.com/7194782/52943914-284aef80-33a9-11e9-84ff-66c75ba7cd09.png)

**Comment by grace5925** [comment]
@wangnan41 刚尝试了在d盘test文件夹下分别起一个叫test11和test的项目，都不行

**Comment by wangnan41** [comment]
@grace5925 我可能解决了，问题出在windows 下 下载地址需要绝对地址，你可以试试0.7.5版本，详细可以可以参看https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js
"As @DanielImfeld pointed it, ENOENT will be thrown if you specify "cwd" in the options, but the given directory does not exist."

**Comment by grace5925** [comment]
@wangnan41 windows下还是报错
![zby23 llyrx 4b ri10z1fp](https://user-images.githubusercontent.com/7194782/53029619-40536980-34a4-11e9-93c4-07ac9d1d8ba2.png)

**Comment by grace5925** [comment]
@wangnan41 换了一台windows电脑，项目文件倒是能下载回来了，但依旧报错，而且这台上在选择依赖的时候，按一次方向键就会多打印一次相同的提示文字，具体见下图

![_20190220002147](https://user-images.githubusercontent.com/7194782/53030498-ddfb6880-34a5-11e9-9dfa-d78a576654b8.png)

![tim 20190220002327](https://user-images.githubusercontent.com/7194782/53030568-0c794380-34a6-11e9-9925-25aa36b7233d.png)

**Comment by wangnan41** [comment]
@grace5925   解决了，0.7.7版本，模板编译不识别一些文件字符串，导致报错。把只编译填模板参数的文件
![timline 20190220104152](https://user-images.githubusercontent.com/9304420/53062568-3198a100-34fc-11e9-8bb8-f0fcec1f85df.png)

**Comment by grace5925** [comment]
@wangnan41 可以了，赞
