### ISSUE TITLE
项目启动卡在bundle finished

### ISSUE THREAD

**Issue by yafengHe** [jdf2e/Gaea4#2]
![image](https://user-images.githubusercontent.com/22092422/52938603-0d727e00-339d-11e9-8c8b-4dcc98b3c68d.png)
node版本：10.12.0

**Comment by wangnan41** [comment]
@yafengHe 
我测试了10.12.0 gaea v0.7.4 版本 没有问题～，
步骤是安装后，npm i ，npm run dll， npm run dev


^CZBMAC-C02VX5TUH:test10 wangnan7$ nvm use 10
Now using node v10.12.0 (npm v6.4.1)
ZBMAC-C02VX5TUH:test10 wangnan7$ npm run dll

> gaea-init@1.0.0 dll /Users/wangnan7/Documents/learn/Test_m/test10
> webpack --config ./webpack.dll.config.js --mode production --hide-modules --progress

clean-webpack-plugin: /Users/wangnan7/Documents/learn/Test_m/test10/static has been removed.
Hash: 51ed96c87b31b49894d0
Version: webpack 4.23.1
Time: 2788ms
Built at: 2019-02-18 17:38:31
           Asset     Size  Chunks             Chunk Names
   vendor.dll.js  108 KiB       0  [emitted]  vendor
vendordev.dll.js  133 KiB       1  [emitted]  vendordev
Entrypoint vendor = vendor.dll.js
Entrypoint vendordev = vendordev.dll.js
ZBMAC-C02VX5TUH:test10 wangnan7$ npm run dev

> gaea-init@1.0.0 dev /Users/wangnan7/Documents/learn/Test_m/test10
>  webpack-dev-server --mode development   -d --open --hide-modules --progress

clean-webpack-plugin: /Users/wangnan7/Documents/learn/Test_m/test10/build has been removed.
 10% building modules 1/1 modules 0 active(node:54227) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/wangnan7/Documents/learn/Test_m/test10/build
ℹ ｢wds｣: 404s will fallback to /index.html
ℹ ｢wdm｣: wait until bundle finished: /
 22% building modules 107/136 modules 29 active ...ode_modules/core-js/modules/_library.js 22% building modules 108/136 modules 28 active ...ode_modules/co 23% building modules 109/136 modules 27 active ...ode_modules/co 23% building modules 110/136 modules 26 active ...ode_modules/co 23% building modules 111/136 modules 25 active ...ode_modules/co 23% building modules 112/136 modules 24 active ...ode_modules/co 23% building modules 113/136 modules 23 active ...ode_modules/co 23% building modules 114/136 modules 22 active ...ode_modules/co 23% building modules 115/136 modules 21 active ...ode_modules/co 23% building modules 116/136 modules 20 active ...ode_modules/co 24% building modules 117/136 modules 19 active ...ode_modules/co 24% building modules 118/136 modules 18 active ...ode_modules/co 24% building modules 119/136 modules 17 active ...ode_modules/co 24% building modules 120/136 modules 16 active ...ode_modules/co 24% building modules 121/136 modules 15 active ...ode_modules/co 24% building modules 122/136 modules 14 active ...ode_modules/co 24% building modules 123/136 modules 13 active ...ode_modules/co 24% building modules 124/136 modules 12 active ...ode_modules/co 25% building modules 125/136 modules 11 active ...ode_modules/co 25% building modules 126/136 modules 10 active ...ode_modules/co 25% building modules 127/136 modules 9 active ...ex=0&id=6edcfd2 25% building modules 127/137 modules 10 active ..._modules/core- 25% building modules 127/138 modules 11 active ...ode_modules/co 25% building modules 127/139 modules 12 active ...modules/core-j 25% building modules 127/140 modules 13 active ..._modules/core- 25% building modules 127/141 modules 14 active ..._modules/core- 25% building modules 127/142 modules 15 active ...0/node_modules 25% building modules 127/143 modules 16 active ...11 from dll-re 25% building modules 128/143 modules 15 active ...0/node_modules 25% building modules 128/144 modules 16 active ...ode_modules/co 25% building modules 128/145 modules 17 active .../core-js/modul 25% building modules 128/146 modules 18 active .../core-js/modul 25% building modules 128/147 modules 19 active ...e_modules/core 25% building modules 128/148 modules 20 active ...ore-js/modules 25% building modules 128/149 modules 21 active ...dules/core-js/ 25% building modules 128/150 modules 22 active ...ode_modules/co 25% building modules 128/151 modules 23 active ...10/node_module 25% building modules 128/152 modules 24 active ..._modules/core- 25% building modules 128/153 modules 25 active ..._modules/core- 25% building modules 128/154 modules 26 active ..._modules/core- 25% building modules 128/155 modules 27 active ...0/node_modules 25% building modules 128/156 modules 28 active ...ules/core-js/m 25% building modules 129/156 modules 27 active ...ules/core-js/m 25% building modules 130/156 modules 26 active ...ules/core-js/m 25% building modules 131/156 modules 25 active ...ules/core-js/m 25% building modules 132/156 modules 24 active ...ules/core-js/m 25% building modules 133/156 modules 23 active ...ules/core-js/m 26% building modules 134/156 modules 22 active ...ules/core-js/m 26% building modules 135/156 modules 21 active ...ules/core-js/m 26% building modules 136/156 modules 20 active ...ules/core-js/m 26% building modules 137/156 modules 19 active ...ules/core-js/m 26% building modules 138/156 modules 18 active ...ules/core-js/m 26% building modules 139/156 modules 17 active ...ules/core-js/m 26% building modules 140/156 modules 16 active ...ules/core-js/m 26% building modules 141/156 modules 15 active ...ules/core-js/m 27% building modules 142/156 modules 14 active ...ules/core-js/m 27% building modules 143/156 modules 13 active ...ules/core-js/m 27% building modules 144/156 modules 12 active ...ules/core-js/m 27% building modules 145/156 modules 11 active ...ules/core-js/m 27% building modules 146/156 modules 10 active ...ules/core-js/m 27% building modules 147/156 modules 9 active ...ex=0&id=6edcfd2 27% building modules 147/157 modules 10 active ...ules/core-js/m 27% building modules 148/157 modules 9 active ...ex=0&id=6edcfd2 27% building modules 149/157 modules 8 active ...ex=0&id=6edcfd2 28% building modules 150/157 modules 7 active ...ex=0&id=6edcfd2 28% building modules 151/157 modules 6 active ...ex=0&id=6edcfd2 28% building modules 152/157 modules 5 active ...Test_m/test10/s 28% building modules 152/158 modules 6 active ...s/core-js/modul 28% building modules 152/159 modules 7 active ...node_modules/cs 28% building modules 152/160 modules 8 active ...de_modules/css- 28% building modules 153/160 modules 7 active ...de_modules/css- 28% building modules 154/160 modules 6 active ...de_modules/css- 28% building modules 155/160 modules 5 active ...Test_m/test10/s 28% building modules 156/160 modules 4 active ...nutui/nutui/dis 28% building modules 156/161 modules 5 active ...rn/Test_m/test1 28% building modules 156/162 modules 6 active ...t_m/test10/src/ 28% building modules 157/162 modules 5 active ...t_m/test10/src/ 28% building modules 158/162 modules 4 active ...t_m/test10/src/ 29% building modules 159/162 modules 3 active ...nutui/nutui/dis 29% building modules 160/162 modules 2 active ...nutui/nutui/dis 29% building modules 161/162 modules 1 active ...dist/packages/dℹ ｢wdm｣: Hash: d2e3f410fb907ff54dfe
Version: webpack 4.23.1
Time: 5831ms
Built at: 2019-02-18 17:38:41
           Asset       Size  Chunks             Chunk Names
      index.html  934 bytes          [emitted]
         js/0.js   31.5 KiB       0  [emitted]
       js/app.js   2.49 MiB     app  [emitted]  app
vendordev.dll.js    133 KiB          [emitted]
Entrypoint app = js/app.js
[0] multi (webpack)-dev-server/client?http://localhost:8080 ./src/app.js 40 bytes {app} [built]
[./node_modules/@nutui/nutui/dist/packages/cell/cell.css] 1.17 KiB {app} [built]
[./node_modules/@nutui/nutui/dist/packages/cell/cell.js] 16.9 KiB {app} [built]
[./node_modules/@nutui/nutui/dist/packages/dialog/dialog.css] 1.17 KiB {app} [built]
[./node_modules/@nutui/nutui/dist/packages/dialog/dialog.js] 90.7 KiB {app} [built]
[./node_modules/loglevel/lib/loglevel.js] 6.84 KiB {app} [built]
[./node_modules/strip-ansi/index.js] 162 bytes {app} [built]
[./node_modules/url/url.js] 22.2 KiB {app} [built]
[./node_modules/vue/dist/vue.runtime.esm.js] 203 KiB {app} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 7.79 KiB {app} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {app} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {app} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {app} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js75 bytes {app} [built]
[./src/app.js] 484 bytes {app} [built]
    + 147 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 1.01 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 492 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 546 bytes {0} [built]
ℹ ｢wdm｣: Compiled successfully.

**Comment by yafengHe** [comment]
好的，谢谢。我重新创建项目未勾选SMock试了下，项目启动成功，我猜是之前勾选了smock但没有在package.json写 相关配置。本以为没写代码这里不加配置也能跑起来~

**Comment by wangnan41** [comment]
@yafengHe  嗯。smock 是的dev server上起服务的
